# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_apimachinery_pkg_apis_meta_v1_owner_reference import IoK8sApimachineryPkgApisMetaV1OwnerReference  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApimachineryPkgApisMetaV1OwnerReference(unittest.TestCase):
    """IoK8sApimachineryPkgApisMetaV1OwnerReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApimachineryPkgApisMetaV1OwnerReference(self):
        """Test IoK8sApimachineryPkgApisMetaV1OwnerReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_apimachinery_pkg_apis_meta_v1_owner_reference.IoK8sApimachineryPkgApisMetaV1OwnerReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
