# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.info_service_api import InfoServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInfoServiceApi(unittest.TestCase):
    """InfoServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.info_service_api.InfoServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_info_service_collect_event(self):
        """Test case for info_service_collect_event

        """
        pass

    def test_info_service_get_info(self):
        """Test case for info_service_get_info

        """
        pass

    def test_info_service_get_user_info(self):
        """Test case for info_service_get_user_info

        """
        pass

    def test_info_service_get_version(self):
        """Test case for info_service_get_version

        """
        pass


if __name__ == '__main__':
    unittest.main()
