# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_argoproj_events_v1alpha1_resource import IoArgoprojEventsV1alpha1Resource  # noqa: E501
from swagger_client.rest import ApiException


class TestIoArgoprojEventsV1alpha1Resource(unittest.TestCase):
    """IoArgoprojEventsV1alpha1Resource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoArgoprojEventsV1alpha1Resource(self):
        """Test IoArgoprojEventsV1alpha1Resource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_argoproj_events_v1alpha1_resource.IoArgoprojEventsV1alpha1Resource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
