# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_k8s_api_core_v1_node_selector import IoK8sApiCoreV1NodeSelector  # noqa: E501
from swagger_client.rest import ApiException


class TestIoK8sApiCoreV1NodeSelector(unittest.TestCase):
    """IoK8sApiCoreV1NodeSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoK8sApiCoreV1NodeSelector(self):
        """Test IoK8sApiCoreV1NodeSelector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_k8s_api_core_v1_node_selector.IoK8sApiCoreV1NodeSelector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
