# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.archived_workflow_service_api import ArchivedWorkflowServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestArchivedWorkflowServiceApi(unittest.TestCase):
    """ArchivedWorkflowServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.archived_workflow_service_api.ArchivedWorkflowServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_archived_workflow_service_delete_archived_workflow(self):
        """Test case for archived_workflow_service_delete_archived_workflow

        """
        pass

    def test_archived_workflow_service_get_archived_workflow(self):
        """Test case for archived_workflow_service_get_archived_workflow

        """
        pass

    def test_archived_workflow_service_list_archived_workflow_label_keys(self):
        """Test case for archived_workflow_service_list_archived_workflow_label_keys

        """
        pass

    def test_archived_workflow_service_list_archived_workflow_label_values(self):
        """Test case for archived_workflow_service_list_archived_workflow_label_values

        """
        pass

    def test_archived_workflow_service_list_archived_workflows(self):
        """Test case for archived_workflow_service_list_archived_workflows

        """
        pass

    def test_archived_workflow_service_resubmit_archived_workflow(self):
        """Test case for archived_workflow_service_resubmit_archived_workflow

        """
        pass

    def test_archived_workflow_service_retry_archived_workflow(self):
        """Test case for archived_workflow_service_retry_archived_workflow

        """
        pass


if __name__ == '__main__':
    unittest.main()
