# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.event_source_service_api import EventSourceServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEventSourceServiceApi(unittest.TestCase):
    """EventSourceServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.event_source_service_api.EventSourceServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_event_source_service_create_event_source(self):
        """Test case for event_source_service_create_event_source

        """
        pass

    def test_event_source_service_delete_event_source(self):
        """Test case for event_source_service_delete_event_source

        """
        pass

    def test_event_source_service_event_sources_logs(self):
        """Test case for event_source_service_event_sources_logs

        """
        pass

    def test_event_source_service_get_event_source(self):
        """Test case for event_source_service_get_event_source

        """
        pass

    def test_event_source_service_list_event_sources(self):
        """Test case for event_source_service_list_event_sources

        """
        pass

    def test_event_source_service_update_event_source(self):
        """Test case for event_source_service_update_event_source

        """
        pass

    def test_event_source_service_watch_event_sources(self):
        """Test case for event_source_service_watch_event_sources

        """
        pass


if __name__ == '__main__':
    unittest.main()
