# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cron_workflow_service_api import CronWorkflowServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCronWorkflowServiceApi(unittest.TestCase):
    """CronWorkflowServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cron_workflow_service_api.CronWorkflowServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cron_workflow_service_create_cron_workflow(self):
        """Test case for cron_workflow_service_create_cron_workflow

        """
        pass

    def test_cron_workflow_service_delete_cron_workflow(self):
        """Test case for cron_workflow_service_delete_cron_workflow

        """
        pass

    def test_cron_workflow_service_get_cron_workflow(self):
        """Test case for cron_workflow_service_get_cron_workflow

        """
        pass

    def test_cron_workflow_service_lint_cron_workflow(self):
        """Test case for cron_workflow_service_lint_cron_workflow

        """
        pass

    def test_cron_workflow_service_list_cron_workflows(self):
        """Test case for cron_workflow_service_list_cron_workflows

        """
        pass

    def test_cron_workflow_service_resume_cron_workflow(self):
        """Test case for cron_workflow_service_resume_cron_workflow

        """
        pass

    def test_cron_workflow_service_suspend_cron_workflow(self):
        """Test case for cron_workflow_service_suspend_cron_workflow

        """
        pass

    def test_cron_workflow_service_update_cron_workflow(self):
        """Test case for cron_workflow_service_update_cron_workflow

        """
        pass


if __name__ == '__main__':
    unittest.main()
