# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class EventsourceLogEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'event_name': 'str',
        'event_source_name': 'str',
        'event_source_type': 'str',
        'level': 'str',
        'msg': 'str',
        'namespace': 'str',
        'time': 'IoK8sApimachineryPkgApisMetaV1Time'
    }

    attribute_map = {
        'event_name': 'eventName',
        'event_source_name': 'eventSourceName',
        'event_source_type': 'eventSourceType',
        'level': 'level',
        'msg': 'msg',
        'namespace': 'namespace',
        'time': 'time'
    }

    def __init__(self, event_name=None, event_source_name=None, event_source_type=None, level=None, msg=None, namespace=None, time=None, _configuration=None):  # noqa: E501
        """EventsourceLogEntry - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._event_name = None
        self._event_source_name = None
        self._event_source_type = None
        self._level = None
        self._msg = None
        self._namespace = None
        self._time = None
        self.discriminator = None

        if event_name is not None:
            self.event_name = event_name
        if event_source_name is not None:
            self.event_source_name = event_source_name
        if event_source_type is not None:
            self.event_source_type = event_source_type
        if level is not None:
            self.level = level
        if msg is not None:
            self.msg = msg
        if namespace is not None:
            self.namespace = namespace
        if time is not None:
            self.time = time

    @property
    def event_name(self):
        """Gets the event_name of this EventsourceLogEntry.  # noqa: E501


        :return: The event_name of this EventsourceLogEntry.  # noqa: E501
        :rtype: str
        """
        return self._event_name

    @event_name.setter
    def event_name(self, event_name):
        """Sets the event_name of this EventsourceLogEntry.


        :param event_name: The event_name of this EventsourceLogEntry.  # noqa: E501
        :type: str
        """

        self._event_name = event_name

    @property
    def event_source_name(self):
        """Gets the event_source_name of this EventsourceLogEntry.  # noqa: E501


        :return: The event_source_name of this EventsourceLogEntry.  # noqa: E501
        :rtype: str
        """
        return self._event_source_name

    @event_source_name.setter
    def event_source_name(self, event_source_name):
        """Sets the event_source_name of this EventsourceLogEntry.


        :param event_source_name: The event_source_name of this EventsourceLogEntry.  # noqa: E501
        :type: str
        """

        self._event_source_name = event_source_name

    @property
    def event_source_type(self):
        """Gets the event_source_type of this EventsourceLogEntry.  # noqa: E501


        :return: The event_source_type of this EventsourceLogEntry.  # noqa: E501
        :rtype: str
        """
        return self._event_source_type

    @event_source_type.setter
    def event_source_type(self, event_source_type):
        """Sets the event_source_type of this EventsourceLogEntry.


        :param event_source_type: The event_source_type of this EventsourceLogEntry.  # noqa: E501
        :type: str
        """

        self._event_source_type = event_source_type

    @property
    def level(self):
        """Gets the level of this EventsourceLogEntry.  # noqa: E501


        :return: The level of this EventsourceLogEntry.  # noqa: E501
        :rtype: str
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this EventsourceLogEntry.


        :param level: The level of this EventsourceLogEntry.  # noqa: E501
        :type: str
        """

        self._level = level

    @property
    def msg(self):
        """Gets the msg of this EventsourceLogEntry.  # noqa: E501


        :return: The msg of this EventsourceLogEntry.  # noqa: E501
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this EventsourceLogEntry.


        :param msg: The msg of this EventsourceLogEntry.  # noqa: E501
        :type: str
        """

        self._msg = msg

    @property
    def namespace(self):
        """Gets the namespace of this EventsourceLogEntry.  # noqa: E501


        :return: The namespace of this EventsourceLogEntry.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this EventsourceLogEntry.


        :param namespace: The namespace of this EventsourceLogEntry.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def time(self):
        """Gets the time of this EventsourceLogEntry.  # noqa: E501


        :return: The time of this EventsourceLogEntry.  # noqa: E501
        :rtype: IoK8sApimachineryPkgApisMetaV1Time
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this EventsourceLogEntry.


        :param time: The time of this EventsourceLogEntry.  # noqa: E501
        :type: IoK8sApimachineryPkgApisMetaV1Time
        """

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EventsourceLogEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventsourceLogEntry):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EventsourceLogEntry):
            return True

        return self.to_dict() != other.to_dict()
