# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojWorkflowV1alpha1OSSArtifact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'access_key_secret': 'IoK8sApiCoreV1SecretKeySelector',
        'bucket': 'str',
        'create_bucket_if_not_present': 'bool',
        'endpoint': 'str',
        'key': 'str',
        'lifecycle_rule': 'IoArgoprojWorkflowV1alpha1OSSLifecycleRule',
        'secret_key_secret': 'IoK8sApiCoreV1SecretKeySelector',
        'security_token': 'str',
        'use_sdk_creds': 'bool'
    }

    attribute_map = {
        'access_key_secret': 'accessKeySecret',
        'bucket': 'bucket',
        'create_bucket_if_not_present': 'createBucketIfNotPresent',
        'endpoint': 'endpoint',
        'key': 'key',
        'lifecycle_rule': 'lifecycleRule',
        'secret_key_secret': 'secretKeySecret',
        'security_token': 'securityToken',
        'use_sdk_creds': 'useSDKCreds'
    }

    def __init__(self, access_key_secret=None, bucket=None, create_bucket_if_not_present=None, endpoint=None, key=None, lifecycle_rule=None, secret_key_secret=None, security_token=None, use_sdk_creds=None, _configuration=None):  # noqa: E501
        """IoArgoprojWorkflowV1alpha1OSSArtifact - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._access_key_secret = None
        self._bucket = None
        self._create_bucket_if_not_present = None
        self._endpoint = None
        self._key = None
        self._lifecycle_rule = None
        self._secret_key_secret = None
        self._security_token = None
        self._use_sdk_creds = None
        self.discriminator = None

        if access_key_secret is not None:
            self.access_key_secret = access_key_secret
        if bucket is not None:
            self.bucket = bucket
        if create_bucket_if_not_present is not None:
            self.create_bucket_if_not_present = create_bucket_if_not_present
        if endpoint is not None:
            self.endpoint = endpoint
        self.key = key
        if lifecycle_rule is not None:
            self.lifecycle_rule = lifecycle_rule
        if secret_key_secret is not None:
            self.secret_key_secret = secret_key_secret
        if security_token is not None:
            self.security_token = security_token
        if use_sdk_creds is not None:
            self.use_sdk_creds = use_sdk_creds

    @property
    def access_key_secret(self):
        """Gets the access_key_secret of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501

        AccessKeySecret is the secret selector to the bucket's access key  # noqa: E501

        :return: The access_key_secret of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :rtype: IoK8sApiCoreV1SecretKeySelector
        """
        return self._access_key_secret

    @access_key_secret.setter
    def access_key_secret(self, access_key_secret):
        """Sets the access_key_secret of this IoArgoprojWorkflowV1alpha1OSSArtifact.

        AccessKeySecret is the secret selector to the bucket's access key  # noqa: E501

        :param access_key_secret: The access_key_secret of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :type: IoK8sApiCoreV1SecretKeySelector
        """

        self._access_key_secret = access_key_secret

    @property
    def bucket(self):
        """Gets the bucket of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501

        Bucket is the name of the bucket  # noqa: E501

        :return: The bucket of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :rtype: str
        """
        return self._bucket

    @bucket.setter
    def bucket(self, bucket):
        """Sets the bucket of this IoArgoprojWorkflowV1alpha1OSSArtifact.

        Bucket is the name of the bucket  # noqa: E501

        :param bucket: The bucket of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :type: str
        """

        self._bucket = bucket

    @property
    def create_bucket_if_not_present(self):
        """Gets the create_bucket_if_not_present of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501

        CreateBucketIfNotPresent tells the driver to attempt to create the OSS bucket for output artifacts, if it doesn't exist  # noqa: E501

        :return: The create_bucket_if_not_present of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :rtype: bool
        """
        return self._create_bucket_if_not_present

    @create_bucket_if_not_present.setter
    def create_bucket_if_not_present(self, create_bucket_if_not_present):
        """Sets the create_bucket_if_not_present of this IoArgoprojWorkflowV1alpha1OSSArtifact.

        CreateBucketIfNotPresent tells the driver to attempt to create the OSS bucket for output artifacts, if it doesn't exist  # noqa: E501

        :param create_bucket_if_not_present: The create_bucket_if_not_present of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :type: bool
        """

        self._create_bucket_if_not_present = create_bucket_if_not_present

    @property
    def endpoint(self):
        """Gets the endpoint of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501

        Endpoint is the hostname of the bucket endpoint  # noqa: E501

        :return: The endpoint of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this IoArgoprojWorkflowV1alpha1OSSArtifact.

        Endpoint is the hostname of the bucket endpoint  # noqa: E501

        :param endpoint: The endpoint of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :type: str
        """

        self._endpoint = endpoint

    @property
    def key(self):
        """Gets the key of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501

        Key is the path in the bucket where the artifact resides  # noqa: E501

        :return: The key of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this IoArgoprojWorkflowV1alpha1OSSArtifact.

        Key is the path in the bucket where the artifact resides  # noqa: E501

        :param key: The key of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501

        self._key = key

    @property
    def lifecycle_rule(self):
        """Gets the lifecycle_rule of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501

        LifecycleRule specifies how to manage bucket's lifecycle  # noqa: E501

        :return: The lifecycle_rule of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :rtype: IoArgoprojWorkflowV1alpha1OSSLifecycleRule
        """
        return self._lifecycle_rule

    @lifecycle_rule.setter
    def lifecycle_rule(self, lifecycle_rule):
        """Sets the lifecycle_rule of this IoArgoprojWorkflowV1alpha1OSSArtifact.

        LifecycleRule specifies how to manage bucket's lifecycle  # noqa: E501

        :param lifecycle_rule: The lifecycle_rule of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :type: IoArgoprojWorkflowV1alpha1OSSLifecycleRule
        """

        self._lifecycle_rule = lifecycle_rule

    @property
    def secret_key_secret(self):
        """Gets the secret_key_secret of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501

        SecretKeySecret is the secret selector to the bucket's secret key  # noqa: E501

        :return: The secret_key_secret of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :rtype: IoK8sApiCoreV1SecretKeySelector
        """
        return self._secret_key_secret

    @secret_key_secret.setter
    def secret_key_secret(self, secret_key_secret):
        """Sets the secret_key_secret of this IoArgoprojWorkflowV1alpha1OSSArtifact.

        SecretKeySecret is the secret selector to the bucket's secret key  # noqa: E501

        :param secret_key_secret: The secret_key_secret of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :type: IoK8sApiCoreV1SecretKeySelector
        """

        self._secret_key_secret = secret_key_secret

    @property
    def security_token(self):
        """Gets the security_token of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501

        SecurityToken is the user's temporary security token. For more details, check out: https://www.alibabacloud.com/help/doc-detail/100624.htm  # noqa: E501

        :return: The security_token of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :rtype: str
        """
        return self._security_token

    @security_token.setter
    def security_token(self, security_token):
        """Sets the security_token of this IoArgoprojWorkflowV1alpha1OSSArtifact.

        SecurityToken is the user's temporary security token. For more details, check out: https://www.alibabacloud.com/help/doc-detail/100624.htm  # noqa: E501

        :param security_token: The security_token of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :type: str
        """

        self._security_token = security_token

    @property
    def use_sdk_creds(self):
        """Gets the use_sdk_creds of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501

        UseSDKCreds tells the driver to figure out credentials based on sdk defaults.  # noqa: E501

        :return: The use_sdk_creds of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :rtype: bool
        """
        return self._use_sdk_creds

    @use_sdk_creds.setter
    def use_sdk_creds(self, use_sdk_creds):
        """Sets the use_sdk_creds of this IoArgoprojWorkflowV1alpha1OSSArtifact.

        UseSDKCreds tells the driver to figure out credentials based on sdk defaults.  # noqa: E501

        :param use_sdk_creds: The use_sdk_creds of this IoArgoprojWorkflowV1alpha1OSSArtifact.  # noqa: E501
        :type: bool
        """

        self._use_sdk_creds = use_sdk_creds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojWorkflowV1alpha1OSSArtifact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1OSSArtifact):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1OSSArtifact):
            return True

        return self.to_dict() != other.to_dict()
