# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'duration': 'str',
        'retries': 'IoK8sApimachineryPkgUtilIntstrIntOrString'
    }

    attribute_map = {
        'duration': 'duration',
        'retries': 'retries'
    }

    def __init__(self, duration=None, retries=None, _configuration=None):  # noqa: E501
        """IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._duration = None
        self._retries = None
        self.discriminator = None

        if duration is not None:
            self.duration = duration
        self.retries = retries

    @property
    def duration(self):
        """Gets the duration of this IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.  # noqa: E501

        Duration is the time between each retry, examples values are \"300ms\", \"1s\" or \"5m\". Valid time units are \"ns\", \"us\" (or \"µs\"), \"ms\", \"s\", \"m\", \"h\".  # noqa: E501

        :return: The duration of this IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.  # noqa: E501
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.

        Duration is the time between each retry, examples values are \"300ms\", \"1s\" or \"5m\". Valid time units are \"ns\", \"us\" (or \"µs\"), \"ms\", \"s\", \"m\", \"h\".  # noqa: E501

        :param duration: The duration of this IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.  # noqa: E501
        :type: str
        """

        self._duration = duration

    @property
    def retries(self):
        """Gets the retries of this IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.  # noqa: E501

        Nbr of retries  # noqa: E501

        :return: The retries of this IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.  # noqa: E501
        :rtype: IoK8sApimachineryPkgUtilIntstrIntOrString
        """
        return self._retries

    @retries.setter
    def retries(self, retries):
        """Sets the retries of this IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.

        Nbr of retries  # noqa: E501

        :param retries: The retries of this IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy.  # noqa: E501
        :type: IoK8sApimachineryPkgUtilIntstrIntOrString
        """
        if self._configuration.client_side_validation and retries is None:
            raise ValueError("Invalid value for `retries`, must not be `None`")  # noqa: E501

        self._retries = retries

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1ContainerSetRetryStrategy):
            return True

        return self.to_dict() != other.to_dict()
