# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojEventsV1alpha1RedisEventSource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channels': 'list[str]',
        'db': 'int',
        'filter': 'IoArgoprojEventsV1alpha1EventSourceFilter',
        'host_address': 'str',
        'json_body': 'bool',
        'metadata': 'dict(str, str)',
        'namespace': 'str',
        'password': 'IoK8sApiCoreV1SecretKeySelector',
        'tls': 'IoArgoprojEventsV1alpha1TLSConfig',
        'username': 'str'
    }

    attribute_map = {
        'channels': 'channels',
        'db': 'db',
        'filter': 'filter',
        'host_address': 'hostAddress',
        'json_body': 'jsonBody',
        'metadata': 'metadata',
        'namespace': 'namespace',
        'password': 'password',
        'tls': 'tls',
        'username': 'username'
    }

    def __init__(self, channels=None, db=None, filter=None, host_address=None, json_body=None, metadata=None, namespace=None, password=None, tls=None, username=None, _configuration=None):  # noqa: E501
        """IoArgoprojEventsV1alpha1RedisEventSource - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._channels = None
        self._db = None
        self._filter = None
        self._host_address = None
        self._json_body = None
        self._metadata = None
        self._namespace = None
        self._password = None
        self._tls = None
        self._username = None
        self.discriminator = None

        if channels is not None:
            self.channels = channels
        if db is not None:
            self.db = db
        if filter is not None:
            self.filter = filter
        if host_address is not None:
            self.host_address = host_address
        if json_body is not None:
            self.json_body = json_body
        if metadata is not None:
            self.metadata = metadata
        if namespace is not None:
            self.namespace = namespace
        if password is not None:
            self.password = password
        if tls is not None:
            self.tls = tls
        if username is not None:
            self.username = username

    @property
    def channels(self):
        """Gets the channels of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The channels of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: list[str]
        """
        return self._channels

    @channels.setter
    def channels(self, channels):
        """Sets the channels of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param channels: The channels of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: list[str]
        """

        self._channels = channels

    @property
    def db(self):
        """Gets the db of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The db of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: int
        """
        return self._db

    @db.setter
    def db(self, db):
        """Sets the db of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param db: The db of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: int
        """

        self._db = db

    @property
    def filter(self):
        """Gets the filter of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The filter of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: IoArgoprojEventsV1alpha1EventSourceFilter
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param filter: The filter of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: IoArgoprojEventsV1alpha1EventSourceFilter
        """

        self._filter = filter

    @property
    def host_address(self):
        """Gets the host_address of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The host_address of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: str
        """
        return self._host_address

    @host_address.setter
    def host_address(self, host_address):
        """Sets the host_address of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param host_address: The host_address of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: str
        """

        self._host_address = host_address

    @property
    def json_body(self):
        """Gets the json_body of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The json_body of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: bool
        """
        return self._json_body

    @json_body.setter
    def json_body(self, json_body):
        """Sets the json_body of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param json_body: The json_body of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: bool
        """

        self._json_body = json_body

    @property
    def metadata(self):
        """Gets the metadata of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The metadata of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param metadata: The metadata of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: dict(str, str)
        """

        self._metadata = metadata

    @property
    def namespace(self):
        """Gets the namespace of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The namespace of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param namespace: The namespace of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def password(self):
        """Gets the password of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The password of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: IoK8sApiCoreV1SecretKeySelector
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param password: The password of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: IoK8sApiCoreV1SecretKeySelector
        """

        self._password = password

    @property
    def tls(self):
        """Gets the tls of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The tls of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: IoArgoprojEventsV1alpha1TLSConfig
        """
        return self._tls

    @tls.setter
    def tls(self, tls):
        """Sets the tls of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param tls: The tls of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: IoArgoprojEventsV1alpha1TLSConfig
        """

        self._tls = tls

    @property
    def username(self):
        """Gets the username of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501


        :return: The username of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this IoArgoprojEventsV1alpha1RedisEventSource.


        :param username: The username of this IoArgoprojEventsV1alpha1RedisEventSource.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojEventsV1alpha1RedisEventSource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojEventsV1alpha1RedisEventSource):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojEventsV1alpha1RedisEventSource):
            return True

        return self.to_dict() != other.to_dict()
