# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojWorkflowV1alpha1ValueFrom(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'config_map_key_ref': 'IoK8sApiCoreV1ConfigMapKeySelector',
        'default': 'str',
        'event': 'str',
        'expression': 'str',
        'jq_filter': 'str',
        'json_path': 'str',
        'parameter': 'str',
        'path': 'str',
        'supplied': 'IoArgoprojWorkflowV1alpha1SuppliedValueFrom'
    }

    attribute_map = {
        'config_map_key_ref': 'configMapKeyRef',
        'default': 'default',
        'event': 'event',
        'expression': 'expression',
        'jq_filter': 'jqFilter',
        'json_path': 'jsonPath',
        'parameter': 'parameter',
        'path': 'path',
        'supplied': 'supplied'
    }

    def __init__(self, config_map_key_ref=None, default=None, event=None, expression=None, jq_filter=None, json_path=None, parameter=None, path=None, supplied=None, _configuration=None):  # noqa: E501
        """IoArgoprojWorkflowV1alpha1ValueFrom - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._config_map_key_ref = None
        self._default = None
        self._event = None
        self._expression = None
        self._jq_filter = None
        self._json_path = None
        self._parameter = None
        self._path = None
        self._supplied = None
        self.discriminator = None

        if config_map_key_ref is not None:
            self.config_map_key_ref = config_map_key_ref
        if default is not None:
            self.default = default
        if event is not None:
            self.event = event
        if expression is not None:
            self.expression = expression
        if jq_filter is not None:
            self.jq_filter = jq_filter
        if json_path is not None:
            self.json_path = json_path
        if parameter is not None:
            self.parameter = parameter
        if path is not None:
            self.path = path
        if supplied is not None:
            self.supplied = supplied

    @property
    def config_map_key_ref(self):
        """Gets the config_map_key_ref of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501

        ConfigMapKeyRef is configmap selector for input parameter configuration  # noqa: E501

        :return: The config_map_key_ref of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :rtype: IoK8sApiCoreV1ConfigMapKeySelector
        """
        return self._config_map_key_ref

    @config_map_key_ref.setter
    def config_map_key_ref(self, config_map_key_ref):
        """Sets the config_map_key_ref of this IoArgoprojWorkflowV1alpha1ValueFrom.

        ConfigMapKeyRef is configmap selector for input parameter configuration  # noqa: E501

        :param config_map_key_ref: The config_map_key_ref of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :type: IoK8sApiCoreV1ConfigMapKeySelector
        """

        self._config_map_key_ref = config_map_key_ref

    @property
    def default(self):
        """Gets the default of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501

        Default specifies a value to be used if retrieving the value from the specified source fails  # noqa: E501

        :return: The default of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :rtype: str
        """
        return self._default

    @default.setter
    def default(self, default):
        """Sets the default of this IoArgoprojWorkflowV1alpha1ValueFrom.

        Default specifies a value to be used if retrieving the value from the specified source fails  # noqa: E501

        :param default: The default of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :type: str
        """

        self._default = default

    @property
    def event(self):
        """Gets the event of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501

        Selector (https://github.com/expr-lang/expr) that is evaluated against the event to get the value of the parameter. E.g. `payload.message`  # noqa: E501

        :return: The event of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :rtype: str
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this IoArgoprojWorkflowV1alpha1ValueFrom.

        Selector (https://github.com/expr-lang/expr) that is evaluated against the event to get the value of the parameter. E.g. `payload.message`  # noqa: E501

        :param event: The event of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :type: str
        """

        self._event = event

    @property
    def expression(self):
        """Gets the expression of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501

        Expression, if defined, is evaluated to specify the value for the parameter  # noqa: E501

        :return: The expression of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :rtype: str
        """
        return self._expression

    @expression.setter
    def expression(self, expression):
        """Sets the expression of this IoArgoprojWorkflowV1alpha1ValueFrom.

        Expression, if defined, is evaluated to specify the value for the parameter  # noqa: E501

        :param expression: The expression of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :type: str
        """

        self._expression = expression

    @property
    def jq_filter(self):
        """Gets the jq_filter of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501

        JQFilter expression against the resource object in resource templates  # noqa: E501

        :return: The jq_filter of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :rtype: str
        """
        return self._jq_filter

    @jq_filter.setter
    def jq_filter(self, jq_filter):
        """Sets the jq_filter of this IoArgoprojWorkflowV1alpha1ValueFrom.

        JQFilter expression against the resource object in resource templates  # noqa: E501

        :param jq_filter: The jq_filter of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :type: str
        """

        self._jq_filter = jq_filter

    @property
    def json_path(self):
        """Gets the json_path of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501

        JSONPath of a resource to retrieve an output parameter value from in resource templates  # noqa: E501

        :return: The json_path of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :rtype: str
        """
        return self._json_path

    @json_path.setter
    def json_path(self, json_path):
        """Sets the json_path of this IoArgoprojWorkflowV1alpha1ValueFrom.

        JSONPath of a resource to retrieve an output parameter value from in resource templates  # noqa: E501

        :param json_path: The json_path of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :type: str
        """

        self._json_path = json_path

    @property
    def parameter(self):
        """Gets the parameter of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501

        Parameter reference to a step or dag task in which to retrieve an output parameter value from (e.g. '{{steps.mystep.outputs.myparam}}')  # noqa: E501

        :return: The parameter of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :rtype: str
        """
        return self._parameter

    @parameter.setter
    def parameter(self, parameter):
        """Sets the parameter of this IoArgoprojWorkflowV1alpha1ValueFrom.

        Parameter reference to a step or dag task in which to retrieve an output parameter value from (e.g. '{{steps.mystep.outputs.myparam}}')  # noqa: E501

        :param parameter: The parameter of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :type: str
        """

        self._parameter = parameter

    @property
    def path(self):
        """Gets the path of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501

        Path in the container to retrieve an output parameter value from in container templates  # noqa: E501

        :return: The path of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this IoArgoprojWorkflowV1alpha1ValueFrom.

        Path in the container to retrieve an output parameter value from in container templates  # noqa: E501

        :param path: The path of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def supplied(self):
        """Gets the supplied of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501

        Supplied value to be filled in directly, either through the CLI, API, etc.  # noqa: E501

        :return: The supplied of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :rtype: IoArgoprojWorkflowV1alpha1SuppliedValueFrom
        """
        return self._supplied

    @supplied.setter
    def supplied(self, supplied):
        """Sets the supplied of this IoArgoprojWorkflowV1alpha1ValueFrom.

        Supplied value to be filled in directly, either through the CLI, API, etc.  # noqa: E501

        :param supplied: The supplied of this IoArgoprojWorkflowV1alpha1ValueFrom.  # noqa: E501
        :type: IoArgoprojWorkflowV1alpha1SuppliedValueFrom
        """

        self._supplied = supplied

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojWorkflowV1alpha1ValueFrom, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1ValueFrom):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1ValueFrom):
            return True

        return self.to_dict() != other.to_dict()
