# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojEventsV1alpha1EventDependencyTransformer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'jq': 'str',
        'script': 'str'
    }

    attribute_map = {
        'jq': 'jq',
        'script': 'script'
    }

    def __init__(self, jq=None, script=None, _configuration=None):  # noqa: E501
        """IoArgoprojEventsV1alpha1EventDependencyTransformer - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._jq = None
        self._script = None
        self.discriminator = None

        if jq is not None:
            self.jq = jq
        if script is not None:
            self.script = script

    @property
    def jq(self):
        """Gets the jq of this IoArgoprojEventsV1alpha1EventDependencyTransformer.  # noqa: E501


        :return: The jq of this IoArgoprojEventsV1alpha1EventDependencyTransformer.  # noqa: E501
        :rtype: str
        """
        return self._jq

    @jq.setter
    def jq(self, jq):
        """Sets the jq of this IoArgoprojEventsV1alpha1EventDependencyTransformer.


        :param jq: The jq of this IoArgoprojEventsV1alpha1EventDependencyTransformer.  # noqa: E501
        :type: str
        """

        self._jq = jq

    @property
    def script(self):
        """Gets the script of this IoArgoprojEventsV1alpha1EventDependencyTransformer.  # noqa: E501


        :return: The script of this IoArgoprojEventsV1alpha1EventDependencyTransformer.  # noqa: E501
        :rtype: str
        """
        return self._script

    @script.setter
    def script(self, script):
        """Sets the script of this IoArgoprojEventsV1alpha1EventDependencyTransformer.


        :param script: The script of this IoArgoprojEventsV1alpha1EventDependencyTransformer.  # noqa: E501
        :type: str
        """

        self._script = script

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojEventsV1alpha1EventDependencyTransformer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojEventsV1alpha1EventDependencyTransformer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojEventsV1alpha1EventDependencyTransformer):
            return True

        return self.to_dict() != other.to_dict()
