# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojWorkflowV1alpha1HTTP(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'body': 'str',
        'body_from': 'IoArgoprojWorkflowV1alpha1HTTPBodySource',
        'headers': 'list[IoArgoprojWorkflowV1alpha1HTTPHeader]',
        'insecure_skip_verify': 'bool',
        'method': 'str',
        'success_condition': 'str',
        'timeout_seconds': 'int',
        'url': 'str'
    }

    attribute_map = {
        'body': 'body',
        'body_from': 'bodyFrom',
        'headers': 'headers',
        'insecure_skip_verify': 'insecureSkipVerify',
        'method': 'method',
        'success_condition': 'successCondition',
        'timeout_seconds': 'timeoutSeconds',
        'url': 'url'
    }

    def __init__(self, body=None, body_from=None, headers=None, insecure_skip_verify=None, method=None, success_condition=None, timeout_seconds=None, url=None, _configuration=None):  # noqa: E501
        """IoArgoprojWorkflowV1alpha1HTTP - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._body = None
        self._body_from = None
        self._headers = None
        self._insecure_skip_verify = None
        self._method = None
        self._success_condition = None
        self._timeout_seconds = None
        self._url = None
        self.discriminator = None

        if body is not None:
            self.body = body
        if body_from is not None:
            self.body_from = body_from
        if headers is not None:
            self.headers = headers
        if insecure_skip_verify is not None:
            self.insecure_skip_verify = insecure_skip_verify
        if method is not None:
            self.method = method
        if success_condition is not None:
            self.success_condition = success_condition
        if timeout_seconds is not None:
            self.timeout_seconds = timeout_seconds
        self.url = url

    @property
    def body(self):
        """Gets the body of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501

        Body is content of the HTTP Request  # noqa: E501

        :return: The body of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this IoArgoprojWorkflowV1alpha1HTTP.

        Body is content of the HTTP Request  # noqa: E501

        :param body: The body of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :type: str
        """

        self._body = body

    @property
    def body_from(self):
        """Gets the body_from of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501

        BodyFrom is  content of the HTTP Request as Bytes  # noqa: E501

        :return: The body_from of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :rtype: IoArgoprojWorkflowV1alpha1HTTPBodySource
        """
        return self._body_from

    @body_from.setter
    def body_from(self, body_from):
        """Sets the body_from of this IoArgoprojWorkflowV1alpha1HTTP.

        BodyFrom is  content of the HTTP Request as Bytes  # noqa: E501

        :param body_from: The body_from of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :type: IoArgoprojWorkflowV1alpha1HTTPBodySource
        """

        self._body_from = body_from

    @property
    def headers(self):
        """Gets the headers of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501

        Headers are an optional list of headers to send with HTTP requests  # noqa: E501

        :return: The headers of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :rtype: list[IoArgoprojWorkflowV1alpha1HTTPHeader]
        """
        return self._headers

    @headers.setter
    def headers(self, headers):
        """Sets the headers of this IoArgoprojWorkflowV1alpha1HTTP.

        Headers are an optional list of headers to send with HTTP requests  # noqa: E501

        :param headers: The headers of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :type: list[IoArgoprojWorkflowV1alpha1HTTPHeader]
        """

        self._headers = headers

    @property
    def insecure_skip_verify(self):
        """Gets the insecure_skip_verify of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501

        InsecureSkipVerify is a bool when if set to true will skip TLS verification for the HTTP client  # noqa: E501

        :return: The insecure_skip_verify of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :rtype: bool
        """
        return self._insecure_skip_verify

    @insecure_skip_verify.setter
    def insecure_skip_verify(self, insecure_skip_verify):
        """Sets the insecure_skip_verify of this IoArgoprojWorkflowV1alpha1HTTP.

        InsecureSkipVerify is a bool when if set to true will skip TLS verification for the HTTP client  # noqa: E501

        :param insecure_skip_verify: The insecure_skip_verify of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :type: bool
        """

        self._insecure_skip_verify = insecure_skip_verify

    @property
    def method(self):
        """Gets the method of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501

        Method is HTTP methods for HTTP Request  # noqa: E501

        :return: The method of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this IoArgoprojWorkflowV1alpha1HTTP.

        Method is HTTP methods for HTTP Request  # noqa: E501

        :param method: The method of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :type: str
        """

        self._method = method

    @property
    def success_condition(self):
        """Gets the success_condition of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501

        SuccessCondition is an expression if evaluated to true is considered successful  # noqa: E501

        :return: The success_condition of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :rtype: str
        """
        return self._success_condition

    @success_condition.setter
    def success_condition(self, success_condition):
        """Sets the success_condition of this IoArgoprojWorkflowV1alpha1HTTP.

        SuccessCondition is an expression if evaluated to true is considered successful  # noqa: E501

        :param success_condition: The success_condition of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :type: str
        """

        self._success_condition = success_condition

    @property
    def timeout_seconds(self):
        """Gets the timeout_seconds of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501

        TimeoutSeconds is request timeout for HTTP Request. Default is 30 seconds  # noqa: E501

        :return: The timeout_seconds of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :rtype: int
        """
        return self._timeout_seconds

    @timeout_seconds.setter
    def timeout_seconds(self, timeout_seconds):
        """Sets the timeout_seconds of this IoArgoprojWorkflowV1alpha1HTTP.

        TimeoutSeconds is request timeout for HTTP Request. Default is 30 seconds  # noqa: E501

        :param timeout_seconds: The timeout_seconds of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :type: int
        """

        self._timeout_seconds = timeout_seconds

    @property
    def url(self):
        """Gets the url of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501

        URL of the HTTP Request  # noqa: E501

        :return: The url of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this IoArgoprojWorkflowV1alpha1HTTP.

        URL of the HTTP Request  # noqa: E501

        :param url: The url of this IoArgoprojWorkflowV1alpha1HTTP.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojWorkflowV1alpha1HTTP, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1HTTP):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1HTTP):
            return True

        return self.to_dict() != other.to_dict()
