# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojWorkflowV1alpha1NodeFlag(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hooked': 'bool',
        'retried': 'bool'
    }

    attribute_map = {
        'hooked': 'hooked',
        'retried': 'retried'
    }

    def __init__(self, hooked=None, retried=None, _configuration=None):  # noqa: E501
        """IoArgoprojWorkflowV1alpha1NodeFlag - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._hooked = None
        self._retried = None
        self.discriminator = None

        if hooked is not None:
            self.hooked = hooked
        if retried is not None:
            self.retried = retried

    @property
    def hooked(self):
        """Gets the hooked of this IoArgoprojWorkflowV1alpha1NodeFlag.  # noqa: E501

        Hooked tracks whether or not this node was triggered by hook or onExit  # noqa: E501

        :return: The hooked of this IoArgoprojWorkflowV1alpha1NodeFlag.  # noqa: E501
        :rtype: bool
        """
        return self._hooked

    @hooked.setter
    def hooked(self, hooked):
        """Sets the hooked of this IoArgoprojWorkflowV1alpha1NodeFlag.

        Hooked tracks whether or not this node was triggered by hook or onExit  # noqa: E501

        :param hooked: The hooked of this IoArgoprojWorkflowV1alpha1NodeFlag.  # noqa: E501
        :type: bool
        """

        self._hooked = hooked

    @property
    def retried(self):
        """Gets the retried of this IoArgoprojWorkflowV1alpha1NodeFlag.  # noqa: E501

        Retried tracks whether or not this node was retried by retryStrategy  # noqa: E501

        :return: The retried of this IoArgoprojWorkflowV1alpha1NodeFlag.  # noqa: E501
        :rtype: bool
        """
        return self._retried

    @retried.setter
    def retried(self, retried):
        """Sets the retried of this IoArgoprojWorkflowV1alpha1NodeFlag.

        Retried tracks whether or not this node was retried by retryStrategy  # noqa: E501

        :param retried: The retried of this IoArgoprojWorkflowV1alpha1NodeFlag.  # noqa: E501
        :type: bool
        """

        self._retried = retried

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojWorkflowV1alpha1NodeFlag, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1NodeFlag):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1NodeFlag):
            return True

        return self.to_dict() != other.to_dict()
