# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojWorkflowV1alpha1CronWorkflowStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'active': 'list[IoK8sApiCoreV1ObjectReference]',
        'conditions': 'list[IoArgoprojWorkflowV1alpha1Condition]',
        'last_scheduled_time': 'IoK8sApimachineryPkgApisMetaV1Time'
    }

    attribute_map = {
        'active': 'active',
        'conditions': 'conditions',
        'last_scheduled_time': 'lastScheduledTime'
    }

    def __init__(self, active=None, conditions=None, last_scheduled_time=None, _configuration=None):  # noqa: E501
        """IoArgoprojWorkflowV1alpha1CronWorkflowStatus - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._active = None
        self._conditions = None
        self._last_scheduled_time = None
        self.discriminator = None

        self.active = active
        self.conditions = conditions
        self.last_scheduled_time = last_scheduled_time

    @property
    def active(self):
        """Gets the active of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.  # noqa: E501

        Active is a list of active workflows stemming from this CronWorkflow  # noqa: E501

        :return: The active of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.  # noqa: E501
        :rtype: list[IoK8sApiCoreV1ObjectReference]
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.

        Active is a list of active workflows stemming from this CronWorkflow  # noqa: E501

        :param active: The active of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.  # noqa: E501
        :type: list[IoK8sApiCoreV1ObjectReference]
        """
        if self._configuration.client_side_validation and active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501

        self._active = active

    @property
    def conditions(self):
        """Gets the conditions of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.  # noqa: E501

        Conditions is a list of conditions the CronWorkflow may have  # noqa: E501

        :return: The conditions of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.  # noqa: E501
        :rtype: list[IoArgoprojWorkflowV1alpha1Condition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.

        Conditions is a list of conditions the CronWorkflow may have  # noqa: E501

        :param conditions: The conditions of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.  # noqa: E501
        :type: list[IoArgoprojWorkflowV1alpha1Condition]
        """
        if self._configuration.client_side_validation and conditions is None:
            raise ValueError("Invalid value for `conditions`, must not be `None`")  # noqa: E501

        self._conditions = conditions

    @property
    def last_scheduled_time(self):
        """Gets the last_scheduled_time of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.  # noqa: E501

        LastScheduleTime is the last time the CronWorkflow was scheduled  # noqa: E501

        :return: The last_scheduled_time of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.  # noqa: E501
        :rtype: IoK8sApimachineryPkgApisMetaV1Time
        """
        return self._last_scheduled_time

    @last_scheduled_time.setter
    def last_scheduled_time(self, last_scheduled_time):
        """Sets the last_scheduled_time of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.

        LastScheduleTime is the last time the CronWorkflow was scheduled  # noqa: E501

        :param last_scheduled_time: The last_scheduled_time of this IoArgoprojWorkflowV1alpha1CronWorkflowStatus.  # noqa: E501
        :type: IoK8sApimachineryPkgApisMetaV1Time
        """
        if self._configuration.client_side_validation and last_scheduled_time is None:
            raise ValueError("Invalid value for `last_scheduled_time`, must not be `None`")  # noqa: E501

        self._last_scheduled_time = last_scheduled_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojWorkflowV1alpha1CronWorkflowStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1CronWorkflowStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1CronWorkflowStatus):
            return True

        return self.to_dict() != other.to_dict()
