# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojWorkflowV1alpha1ArtifactNodeSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'archive_location': 'IoArgoprojWorkflowV1alpha1ArtifactLocation',
        'artifacts': 'dict(str, IoArgoprojWorkflowV1alpha1Artifact)'
    }

    attribute_map = {
        'archive_location': 'archiveLocation',
        'artifacts': 'artifacts'
    }

    def __init__(self, archive_location=None, artifacts=None, _configuration=None):  # noqa: E501
        """IoArgoprojWorkflowV1alpha1ArtifactNodeSpec - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._archive_location = None
        self._artifacts = None
        self.discriminator = None

        if archive_location is not None:
            self.archive_location = archive_location
        if artifacts is not None:
            self.artifacts = artifacts

    @property
    def archive_location(self):
        """Gets the archive_location of this IoArgoprojWorkflowV1alpha1ArtifactNodeSpec.  # noqa: E501

        ArchiveLocation is the template-level Artifact location specification  # noqa: E501

        :return: The archive_location of this IoArgoprojWorkflowV1alpha1ArtifactNodeSpec.  # noqa: E501
        :rtype: IoArgoprojWorkflowV1alpha1ArtifactLocation
        """
        return self._archive_location

    @archive_location.setter
    def archive_location(self, archive_location):
        """Sets the archive_location of this IoArgoprojWorkflowV1alpha1ArtifactNodeSpec.

        ArchiveLocation is the template-level Artifact location specification  # noqa: E501

        :param archive_location: The archive_location of this IoArgoprojWorkflowV1alpha1ArtifactNodeSpec.  # noqa: E501
        :type: IoArgoprojWorkflowV1alpha1ArtifactLocation
        """

        self._archive_location = archive_location

    @property
    def artifacts(self):
        """Gets the artifacts of this IoArgoprojWorkflowV1alpha1ArtifactNodeSpec.  # noqa: E501

        Artifacts maps artifact name to Artifact description  # noqa: E501

        :return: The artifacts of this IoArgoprojWorkflowV1alpha1ArtifactNodeSpec.  # noqa: E501
        :rtype: dict(str, IoArgoprojWorkflowV1alpha1Artifact)
        """
        return self._artifacts

    @artifacts.setter
    def artifacts(self, artifacts):
        """Sets the artifacts of this IoArgoprojWorkflowV1alpha1ArtifactNodeSpec.

        Artifacts maps artifact name to Artifact description  # noqa: E501

        :param artifacts: The artifacts of this IoArgoprojWorkflowV1alpha1ArtifactNodeSpec.  # noqa: E501
        :type: dict(str, IoArgoprojWorkflowV1alpha1Artifact)
        """

        self._artifacts = artifacts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojWorkflowV1alpha1ArtifactNodeSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1ArtifactNodeSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojWorkflowV1alpha1ArtifactNodeSpec):
            return True

        return self.to_dict() != other.to_dict()
