# coding: utf-8

"""
    Argo Workflows API

    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/release-3.5/  # noqa: E501

    OpenAPI spec version: VERSION
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class IoArgoprojEventsV1alpha1FileEventSource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'event_type': 'str',
        'filter': 'IoArgoprojEventsV1alpha1EventSourceFilter',
        'metadata': 'dict(str, str)',
        'polling': 'bool',
        'watch_path_config': 'IoArgoprojEventsV1alpha1WatchPathConfig'
    }

    attribute_map = {
        'event_type': 'eventType',
        'filter': 'filter',
        'metadata': 'metadata',
        'polling': 'polling',
        'watch_path_config': 'watchPathConfig'
    }

    def __init__(self, event_type=None, filter=None, metadata=None, polling=None, watch_path_config=None, _configuration=None):  # noqa: E501
        """IoArgoprojEventsV1alpha1FileEventSource - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._event_type = None
        self._filter = None
        self._metadata = None
        self._polling = None
        self._watch_path_config = None
        self.discriminator = None

        if event_type is not None:
            self.event_type = event_type
        if filter is not None:
            self.filter = filter
        if metadata is not None:
            self.metadata = metadata
        if polling is not None:
            self.polling = polling
        if watch_path_config is not None:
            self.watch_path_config = watch_path_config

    @property
    def event_type(self):
        """Gets the event_type of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501


        :return: The event_type of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :rtype: str
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type):
        """Sets the event_type of this IoArgoprojEventsV1alpha1FileEventSource.


        :param event_type: The event_type of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :type: str
        """

        self._event_type = event_type

    @property
    def filter(self):
        """Gets the filter of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501


        :return: The filter of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :rtype: IoArgoprojEventsV1alpha1EventSourceFilter
        """
        return self._filter

    @filter.setter
    def filter(self, filter):
        """Sets the filter of this IoArgoprojEventsV1alpha1FileEventSource.


        :param filter: The filter of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :type: IoArgoprojEventsV1alpha1EventSourceFilter
        """

        self._filter = filter

    @property
    def metadata(self):
        """Gets the metadata of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501


        :return: The metadata of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this IoArgoprojEventsV1alpha1FileEventSource.


        :param metadata: The metadata of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :type: dict(str, str)
        """

        self._metadata = metadata

    @property
    def polling(self):
        """Gets the polling of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501


        :return: The polling of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :rtype: bool
        """
        return self._polling

    @polling.setter
    def polling(self, polling):
        """Sets the polling of this IoArgoprojEventsV1alpha1FileEventSource.


        :param polling: The polling of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :type: bool
        """

        self._polling = polling

    @property
    def watch_path_config(self):
        """Gets the watch_path_config of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501


        :return: The watch_path_config of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :rtype: IoArgoprojEventsV1alpha1WatchPathConfig
        """
        return self._watch_path_config

    @watch_path_config.setter
    def watch_path_config(self, watch_path_config):
        """Sets the watch_path_config of this IoArgoprojEventsV1alpha1FileEventSource.


        :param watch_path_config: The watch_path_config of this IoArgoprojEventsV1alpha1FileEventSource.  # noqa: E501
        :type: IoArgoprojEventsV1alpha1WatchPathConfig
        """

        self._watch_path_config = watch_path_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IoArgoprojEventsV1alpha1FileEventSource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojEventsV1alpha1FileEventSource):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojEventsV1alpha1FileEventSource):
            return True

        return self.to_dict() != other.to_dict()
